name: Release

on:
  pull_request:
  push:
    branches: ['master']
    tags: ['v*']
  schedule:
  - cron: '0 0 * * 0'

jobs:
  release:
    name: release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.*'
    - run: dotnet publish -c Release --self-contained --runtime win-x86 .\OhmGraphite\
    - name: Set artifact name
      shell: bash
      working-directory: OhmGraphite\bin
      run: |
        echo "ARTIFACT_NAME=$(echo *.zip)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        path: OhmGraphite\bin\*.zip
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: False
        title: "Latest Build"
        files: 'OhmGraphite\bin\*.zip'
